### ISSUE TITLE
Illegal operation -o pipefail

### ISSUE THREAD

**Issue by jonathanschaaij** [yorikvanhavre/openscad-thumbnailers#2]
I tried to install it in Linux Mint, which uses nemo.
However it was not working after a little bit of research I found that the problem was in stl2png.sh.

The issue is on line 3 : set -euo pipefail

As a workaround I tried to delete the line, which resolved the issue. 
I am not sure if this is only the case on linux mint or due to some new bash update.
I have not tried whether scad2png.sh has the same problem.

**Comment by yorikvanhavre** [comment]
Thanks for notifying! This line was basically copy/pasted from elsewhere IIRC... In any case none of the -euo options is used in the script, so I think it's safe to remove. Done in 73ab342
